version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - printf '[{"name":"app","imageUri":"%s"}]' $AWS_ECR_REPO > imagedefinitions.json
      - docker build -t app .
      - docker tag app $AWS_ECR_REPO
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ECR_REPO

artifacts:
  files:
    - imagedefinitions.json
